Splitting up about page
Mobistudy/Mobistudyapp pull request #106
Opened 2020-12-04 10:19 UTC by JohnHakansson

About page split up into several pages.

2020-12-04 14:49 UTC, dariosalvi78 requested changes

2020-12-04 14:49 UTC, dariosalvi78 commented on src/pages/about/Contact.vue
> +    <div class="row justify-center">
this div is empty

2020-12-04 14:49 UTC, dariosalvi78 commented on src/pages/about/Contact.vue
> +    <div>
remove this and just put the contact email in the info.contact text?

2020-12-04 14:49 UTC, dariosalvi78 commented on src/router/routes.js
> +    component: () => import('layouts/HomeLayout.vue'),
you can create a new layout for this with a different header on top that says "About" or smth like that

2020-12-04 14:49 UTC, dariosalvi78 commented on src/pages/about/AboutPrivacyPolicy.vue
> +      <div class="row justify-center">
if About is going to be in the header above, maybe this can be removed?

2020-12-04 14:49 UTC, dariosalvi78 commented on src/pages/about/Acknowledgements.vue
> +      <div class="text-h5 q-mt-lg">
same here, if you change layout this can go away maybe

2020-12-04 14:49 UTC, dariosalvi78 commented on src/pages/about/Introduction.vue
> +      <div class="text-h5 q-mt-lg">
same...

2020-12-04 14:49 UTC, dariosalvi78 commented on src/i18n/en/en.js
> -    center, Malmö University.`
shall we call this section "about" instead of "info" ?

2020-12-07 13:41 UTC, HeyOooh commented on src/router/routes.js
> +    component: () => import('layouts/HomeLayout.vue'),
So you would like the header to be the Mobistudy logo and the word about? All the other tabs task, profile etc are the logo + Mobistudy.

2020-12-07 13:44 UTC, HeyOooh commented on src/pages/about/Contact.vue
> +    <div>
We do not understand what you mean, we use the string in the contact for the button and in the header. Could you clarify what you mean please?

2020-12-07 13:55 UTC, dariosalvi78 commented on src/router/routes.js
> +    component: () => import('layouts/HomeLayout.vue'),
mmm, OK I see what you mean, it would look strange because the menu on the bottom is still there (which doesn't happen in the tasks).
Leave it with the logo and Mobsitudy then!

2020-12-07 13:59 UTC, dariosalvi78 commented on src/pages/about/Contact.vue
> +    <div>
I mean that `info.contact` could contain `info.contactEmail` in the same text.
It's just a minor thing, you can leave it as it is if you prefer.

2020-12-07 19:18 UTC, dariosalvi78 commented
didn't we say that we can leave the home layout?

2020-12-08 13:25 UTC, dariosalvi78 requested changes

2020-12-08 13:25 UTC, dariosalvi78 commented on quasar.conf.js
>          if (config.STORAGE.toLowerCase() === 'local') cfg.resolve.alias['modules/storage'] = 'modules/storage.local'
can you uncomment this please?

2020-12-09 08:54 UTC, merged