Questionnaire number answer type and freeText option
Mobistudy/Mobistudyapp pull request #146
Opened 2021-04-01 23:02 UTC by kevinchtsang

Additional answer options for Forms, number answer type and the includeFreeText flag for single and multiple choice. Used in "other" option in questionnaires.

2021-04-02 11:45 UTC, dariosalvi78 requested changes
hey Kevin, great job! and very fast as well! I wish you were my student :)
have a look at the comments: it's all opinions, so I'm happy if you disagree! feel free to ignore them

2021-04-02 11:45 UTC, dariosalvi78 commented on src/pages/tasks/form/Form.vue
> +              val => val !== null && val !== '' || $t('studies.tasks.form.freeTextExplanation'),
in general, the user should be able to skip an answer, so an empty answer should be allowed. Maybe we can remove the rule `val => val !== null && val !== '' || $t('studies.tasks.form.freeTextExplanation')` ?

2021-04-02 11:45 UTC, dariosalvi78 commented on src/pages/tasks/form/Form.vue
> +              v-show="singleChoiceAnswer == answerChoice.id && answerChoice.includeFreeText"
instead of a v-show, we could leave the input field visible but disabled (or read-only), for example: `:disable="singleChoiceAnswer == answerChoice.id && answerChoice.includeFreeText"` so the interface doesn't "jump" too much?

2021-04-02 11:45 UTC, dariosalvi78 commented on src/pages/tasks/form/Form.vue
> +              v-show="multiChoiceAnswer.includes(answerChoice.id) && answerChoice.includeFreeText"
same here: disable instead of show? let's try it...

2021-04-02 11:45 UTC, dariosalvi78 commented on src/pages/tasks/form/Form.vue
> +              answerText: chosenAnswerChoice.text,
wouldn't it be easier if we stored the free text answer in there?

2021-04-02 11:45 UTC, dariosalvi78 commented on src/pages/tasks/form/Form.vue
> +              answerText: chosenAnswerChoice.text,
same as above

2021-04-09 14:42 UTC, kevinchtsang commented on src/pages/tasks/form/Form.vue
> +              answerText: chosenAnswerChoice.text,
not sure what you mean

2021-04-09 14:56 UTC, kevinchtsang commented on src/pages/tasks/form/Form.vue
> +              answerText: chosenAnswerChoice.text,
I think the multichoice free text option should include the original answer appended to the free text answer. The current method of storage is slightly easier to parse for the lastResponse.

2021-04-09 18:48 UTC, dariosalvi78 commented on src/pages/tasks/form/Form.vue
> +              answerText: chosenAnswerChoice.text,
yes, but if you want to include the text of the choice then it's complicated to keep it separated when one goes back in the question. I am also ok to leave it as an extra field in the answer's object

2021-04-09 18:50 UTC, merged