Add "select all toggles" button in consents page
Mobistudy/Mobistudyapp pull request #329
Opened 2023-07-03 21:43 UTC by gentymeri

2023-07-04 07:11 UTC, dariosalvi78 requested changes
there is a problem with this, some of the consent items should trigger the process to obtain OS-level permissions to access APIs. You need to make sure that those permissions are actually triggered when doing "select all".  You can check that in the browser emulation too.

2023-07-04 07:11 UTC, dariosalvi78 commented on src/components/Consents.vue
> +    <button @click="selectAllToggles">Select All</button>
strings literals must always be in the translation files

2023-07-04 07:11 UTC, dariosalvi78 commented on src/components/Consents.vue
> +    selectAllToggles () {
make sure that all OS level permissions are triggered

2023-07-07 10:00 UTC, gentymeri commented on src/components/Consents.vue
> +    selectAllToggles () {
pushed a fix for this

2023-07-17 20:29 UTC, merged